### ISSUE TITLE
Further discussion on choice of priors for GP hyperparameters

### ISSUE THREAD

**Issue by shbhuk** [exoplanet-dev/celerite2#10]
**Is your feature request related to a problem? Please describe.**
Hi, could you discuss the different priors you use for the GP hyperparameters, be it the SHO kernel for the transit case studies, or the rotation kernel in the stellar variability case.  They tend to differ in terms of the functional form as well as starting value. It would be useful to have some discussion on this.

**Comment by dfm** [comment]
I moved this here from exoplanet since this is a celerite2 question rather than an exoplanet one.

There aren't any general rules except that priors should represent your beliefs about the world. It's beyond the scope of these docs to discuss choices of prior in detail. In all the docs, the prior distributions are chosen to be relatively "uninformative", but this will certainly depend on your use case. It's always a good idea to check how sensitive your results are to your specific choices. Again - this is way beyond the scope of these docs.
