### ISSUE TITLE
RotationTerm translated to celerite (set_parameter_vector() input parameters, question).

### ISSUE THREAD

**Issue by 3fon3fonov** [exoplanet-dev/celerite2#44]
When we initialize the doubleSHO, a.k.a. RotationTerm in celrite2, we need (*, sigma, period, Q0, dQ, f). I understand that the idea is to pass five parameters that are will be converted to S1, w1, Q1, S2, w2, Q2 needed for each SHO kernel. So, far so good!

However, I am trying to do is to build this kernel in celerite. See here, under "double_SHOTerm()"

https://github.com/3fon3fonov/exostriker/blob/exostriker-ready/exostriker/lib/RV_mod/GP_kernels.py

My doubt is that use inside the opt.func/mcmc/nested sampling one needs to continuously update the GP while it samples, and compute()

```
...
gps.set_parameter_vector([sampled GP params])
gps.compute()
...

```
however, it seems that set_parameter_vector() seems to expect six parameters, these being the 2xSHO parameters, is that right?

So to update the GP model I need six parameters (which BTW, must always be the individual 2xSHOTerm() in log!), but I sample five, which are; sigma, period, Q0, dQ, and f.  If I understand correctly, the way how is done now, inside the loop/sample run I must always initialize the GP and then compute(). 

I wrote a simple function 

```

def init_dSHOKernel(params):
    kernel =GP_kernels.double_SHOTerm(
            sigma_dSHO=params[0],
            period_dSHO=params[1],
            Q0_dSHO=params[2],
            dQ_dSHO=params[3], 
            f_dSHO=params[4])


    gps = celerite.GP(kernel, mean=0.0)
    return gps
...
#and then during the sampling:
gps = init_dSHOKernel(param_vect)
gps.compute()

```

This seems to work but is quite a compromise, I think. Any comments on this will be highly appreciated. For example, how is this done in celerite2? I will eventually migrate to celerite2, but I would like to have the the option to use the original version too with more kernels.

**Comment by dfm** [comment]
For o.g. celerite, the implementation is a bit tricker than in celerite2, but something like the following should do the trick (I don't think the parameters are identical, but perhaps it's enough to get you started?): https://github.com/dfm/rotate/blob/9c62039b21edc90bd09b6466e8000fd2fb7329ea/rotate/rotation_term.py#L37-L73

Your proposed `init_...` function method is the recommended approach for celerite2 because (by design) celerite2 does not have any model building support. This is because it's meant to be used with a different framework like PyMC, numpyro, or similar. The earlier `get/set_parameter_vector` implementation was brittle and hard to maintain.

**Comment by 3fon3fonov** [comment]
Thanks for pointing to this code! It is definitely a useful start.

However, did I understood correctly that my celerite2-like implementation of the doubeSHO kernel is acceptable? I tested it and it seems that this kernel within the Exo-Striker produces a reasonable output, although I haven't found the time to compare with a pure celerite2 setup. The only caveat I see is that I must initialize the GP with each iteration and I am not quite sure how much overhead that's adding. I would assume that if initialized only once and then updated with  set_parameter_vector() would be a faster/optimal solution.

**Comment by dfm** [comment]
Yeah that's all correct: it should be fine but probably a little less efficient to do what you're doing with original celerite. The gradients won't be computed correctly (this is solvable but annoying; one of the big motivations for celerite2 in the first place!) but otherwise there's nothing wrong with what you're doing!

**Comment by 3fon3fonov** [comment]
Closed!
