### ISSUE TITLE
Pointwise predictive accuracy

### ISSUE THREAD

**Issue by bmorris3** [exoplanet-dev/celerite2#60]
Hi @dfm, 

I'm interested in doing model comparison with LOO-CV and/or WAIC via arviz. My model (w/ JAX+numpyro) relies on celerite2 for computing the log likelihood. The likelihood returned by celerite2 is a single value, but the pointwise predictive accuracy methods expect pointwise logp's. I think that's why when comparing models, I get warnings that say things like: 
```
The point-wise LOO is the same with the sum LOO, please double check the Observed RV in your 
model to make sure it returns element-wise logp.
```
But I'm not sure that a logp can be defined element-wise for a GP. So: is there a way to get element-wise logp's from a GP?

Thanks as always!

**Comment by dfm** [comment]
It's not entirely trivial to do cross validation for GP models since every data point "cares" about whether or not every other data point is included. There isn't really any such thing as a "pointwise" logp for a GP! You can take a look at [section 5.4.2 of R&W](http://www.gaussianprocess.org/gpml/chapters/RW5.pdf) for some general discussion of how you can compute cross validation scores for GPs, but it's not completely obvious that you can do this calculation in a scalable way, or that it would slot into arviz the way you want.

**Comment by bmorris3** [comment]
Thanks for that R&W section, I'm going to read it carefully. I agree that it probably won't translate into a few-line arviz call, but I was wondering if it would be reasonable to do this calculation at all. The R&W passage makes it sound feasible, so maybe there is hope! 

Perhaps a better question is if I'm being distracted by CV methods, and perhaps there's something better suited to GPs?

**Comment by dfm** [comment]
I think it's a totally sensible thing to do!

**Comment by bmorris3** [comment]
I think I've sorted this out and can close the issue, thanks Dan!
